
// Generated by CharPad C64 - Subchrist Software, 2003 - 2023.
// Assemble with 64TASS or similar.


// Display mode : Text (Multi-colour).
// Matrix colouring method : Per Project.


// Colour values...

.var COLR_VIC_BG0 = 11
.var COLR_VIC_BG1 = 11
.var COLR_VIC_BG2 = 14
.var COLR_CMLO_BASE = 3


// Quantities and dimensions...

.var CHAR_COUNT = 256
.var TILE_COUNT = 256
.var TILE_WID = 2
.var TILE_HEI = 2
.var MAP_WID = 80
.var MAP_HEI = 11
.var MAP_WID_CHRS = 160
.var MAP_HEI_CHRS = 22
.var MAP_WID_PXLS = 1280
.var MAP_HEI_PXLS = 176


// Data block sizes (in bytes)...

.var SZ_CHARSET_DATA = 2048 // ($800)
.var SZ_CHARSET_ATTRIB_DATA = 256 // ($100)
.var SZ_TILESET_DATA = 1024 // ($400)
.var SZ_MAP_DATA = 880 // ($370)


// Data block addresses (dummy values)...

.var addr_charset_data = $1000
.var addr_charset_attrib_L1_data = $1000
.var addr_chartileset_data = $1000
.var addr_chartileset_tag_data = $1000
.var addr_map_data = $1000




