
// Generated by SpritePad C64 - Subchrist Software, 2003-2025.
// Assemble with 64TASS or similar.


// Colour values...

.const spritesbatch2_COLR_VIC_SCREEN = 15
.const spritesbatch2_COLR_VIC_SPRITE_MC1 = 1
.const spritesbatch2_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.const spritesbatch2_SPRITE_COUNT = 14


// Data block sizes (in bytes)...

.const spritesbatch2_SZ_SPRITESET_DATA = 896
.const spritesbatch2_SZ_SPRITESET_ATTRIB_DATA = 14


// Data block addresses (dummy values)...

.const spritesbatch2_addr_spritesbatch2_spriteset_data = $1000
.const spritesbatch2_addr_spritesbatch2_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 14 images, 64 bytes per image, total size is 896 ($380) bytes.

spritesbatch2_spriteset_data:

spritesbatch2_sprite_image_0:
.byte $00,$00,$00,$c0,$00,$00,$30,$00,$00,$30,$20,$00,$f3,$f0,$00,$ce
.byte $94,$00,$3e,$ac,$00,$3f,$ff,$00,$0c,$30,$00,$03,$0c,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_1:
.byte $c0,$00,$00,$c0,$00,$00,$c0,$20,$00,$c3,$f0,$00,$fe,$94,$00,$3e
.byte $ac,$00,$3f,$ff,$00,$0c,$30,$00,$0f,$3c,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_2:
.byte $00,$00,$00,$30,$00,$00,$30,$00,$00,$c0,$20,$00,$c3,$f0,$00,$ce
.byte $94,$00,$fe,$ac,$00,$3f,$ff,$00,$0c,$30,$00,$30,$c0,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_3:
.byte $00,$00,$00,$00,$03,$00,$00,$0c,$00,$08,$0c,$00,$0f,$cf,$00,$16
.byte $b3,$00,$3a,$bc,$00,$ff,$fc,$00,$0c,$30,$00,$30,$c0,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_4:
.byte $00,$03,$00,$00,$03,$00,$08,$03,$00,$0f,$c3,$00,$16,$bf,$00,$3a
.byte $bc,$00,$ff,$fc,$00,$0c,$30,$00,$3c,$f0,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_5:
.byte $00,$00,$00,$00,$0c,$00,$00,$0c,$00,$08,$03,$00,$0f,$c3,$00,$16
.byte $b3,$00,$3a,$bf,$00,$ff,$fc,$00,$0c,$30,$00,$03,$0c,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_6:
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$f6,$6f,$00,$3a,$ac,$00,$fc,$3f,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8b

spritesbatch2_sprite_image_7:
.byte $f0,$00,$3c,$30,$30,$30,$3c,$fc,$f0,$0f,$ff,$c0,$c3,$ff,$0c,$ff
.byte $ff,$fc,$03,$ff,$00,$3f,$77,$f0,$f3,$bb,$3c,$0f,$ff,$c0,$3f,$ff
.byte $f0,$f0,$cc,$3c,$00,$cc,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_8:
.byte $00,$30,$00,$fc,$fc,$fc,$0f,$ff,$c0,$03,$ff,$00,$3f,$ff,$f0,$c3
.byte $ff,$0c,$0f,$77,$c0,$33,$bb,$30,$c3,$ff,$0c,$0f,$ff,$c0,$30,$cc
.byte $30,$30,$cc,$30,$c0,$00,$0c,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_9:
.byte $00,$00,$00,$00,$30,$00,$00,$fc,$00,$0f,$ff,$c0,$33,$ff,$30,$cf
.byte $ff,$cc,$33,$ff,$30,$cf,$77,$cc,$33,$bb,$30,$33,$ff,$30,$cf,$ff
.byte $cc,$0c,$cc,$c0,$30,$cc,$30,$30,$00,$30,$c0,$00,$0c,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_10:
.byte $f0,$00,$3c,$30,$cc,$30,$3c,$cc,$f0,$0f,$ff,$c0,$c3,$ff,$0c,$ff
.byte $bb,$fc,$03,$77,$00,$3f,$ff,$f0,$f3,$ff,$3c,$0f,$ff,$c0,$3f,$ff
.byte $f0,$f0,$fc,$3c,$00,$30,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_11:
.byte $00,$cc,$00,$fc,$cc,$fc,$0f,$ff,$c0,$03,$ff,$00,$3f,$bb,$f0,$c3
.byte $77,$0c,$0f,$ff,$c0,$33,$ff,$30,$c3,$ff,$0c,$0f,$ff,$c0,$30,$fc
.byte $30,$30,$30,$30,$c0,$00,$0c,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_12:
.byte $00,$00,$00,$00,$cc,$00,$00,$cc,$00,$0f,$ff,$c0,$33,$ff,$30,$cf
.byte $bb,$cc,$33,$77,$30,$cf,$ff,$cc,$33,$ff,$30,$33,$ff,$30,$cf,$ff
.byte $cc,$0c,$fc,$c0,$30,$30,$30,$30,$00,$30,$c0,$00,$0c,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82

spritesbatch2_sprite_image_13:
.byte $00,$00,$00,$00,$cc,$00,$0f,$ff,$80,$ef,$7b,$cc,$3b,$b7,$b0,$cf
.byte $ff,$ec,$3b,$ee,$30,$cf,$ff,$ec,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$82



// SpriteSet Attribute Data...
// 14 attributes, 1 per image, 8 bits each, total size is 14 ($e) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spritesbatch2_spriteset_attrib_data:

.byte $8b,$8b,$8b,$8b,$8b,$8b,$8b,$82,$82,$82,$82,$82,$82,$82


