
// Generated by SpritePad C64 - Subchrist Software, 2003 - 2023.
// Assemble with 64TASS or similar.


// Colour values...

.const spritesbatch1_COLR_VIC_SCREEN = 15
.const spritesbatch1_COLR_VIC_SPRITE_MC1 = 1
.const spritesbatch1_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.const spritesbatch1_SPRITE_COUNT = 12


// Data block sizes (in bytes)...

.const spritesbatch1_SZ_SPRITESET_DATA = 768
.const spritesbatch1_SZ_SPRITESET_ATTRIB_DATA = 12


// Data block addresses (dummy values)...

.const spritesbatch1_addr_spritesbatch1_spriteset_data = $1000
.const spritesbatch1_addr_spritesbatch1_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 12 images, 64 bytes per image, total size is 768 ($300) bytes.

spritesbatch1_spriteset_data:

spritesbatch1_sprite_image_0:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$AF,$E8,$00,$8F,$C8,$00,$0C,$C0,$00
.byte $0C,$C0,$00,$0C,$C0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_1:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$07,$00,$00,$15,$C8
.byte $00,$25,$68,$00,$05,$00,$00,$0F,$00,$00,$3F,$00,$00,$3F,$00,$00
.byte $73,$00,$00,$73,$C0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_2:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$08,$00,$05,$E0,$00,$15,$C0,$00,$27,$40
.byte $00,$2D,$00,$00,$85,$00,$00,$8F,$C0,$00,$0F,$F0,$00,$0C,$F0,$00
.byte $3D,$C0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8A

spritesbatch1_sprite_image_3:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$05,$E0,$00,$1D,$E0
.byte $00,$27,$40,$00,$A5,$00,$00,$85,$00,$00,$0F,$00,$00,$0F,$00,$00
.byte $0F,$C4,$00,$7F,$F4,$00,$7C,$D0,$00,$40,$50,$00,$40,$00,$00,$8A

spritesbatch1_sprite_image_4:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$03,$40,$00,$8D,$50
.byte $00,$A5,$60,$00,$01,$40,$00,$03,$C0,$00,$03,$F0,$00,$03,$F0,$00
.byte $03,$34,$00,$0F,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_5:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$08,$00,$05,$E0,$00,$15,$C0,$00,$27,$40
.byte $00,$2D,$00,$00,$85,$00,$00,$8F,$C0,$00,$0F,$F0,$00,$0C,$F0,$00
.byte $3D,$C0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8A

spritesbatch1_sprite_image_6:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$AF,$E8,$00,$8F,$C8,$00,$0C,$C0,$00
.byte $0C,$C0,$00,$0C,$C0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_7:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$03,$40,$00,$8D,$50
.byte $00,$A5,$60,$00,$01,$40,$00,$03,$C0,$00,$03,$F0,$00,$03,$F0,$00
.byte $03,$34,$00,$0F,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_8:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$82,$00,$00,$2D,$40,$00,$0D,$50,$00,$07,$60
.byte $00,$01,$E0,$00,$01,$48,$00,$0F,$C8,$00,$3F,$C0,$00,$3C,$C0,$00
.byte $0D,$F0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8A

spritesbatch1_sprite_image_9:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$2D,$40,$00,$2D,$D0
.byte $00,$07,$60,$00,$01,$68,$00,$01,$48,$00,$03,$C0,$00,$03,$C0,$00
.byte $4F,$C0,$00,$7F,$F4,$00,$1C,$F4,$00,$14,$04,$00,$00,$04,$00,$8A

spritesbatch1_sprite_image_10:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$07,$00,$00,$15,$C8
.byte $00,$25,$68,$00,$05,$00,$00,$0F,$00,$00,$3F,$00,$00,$3F,$00,$00
.byte $73,$00,$00,$73,$C0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_11:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$82,$00,$00,$2D,$40,$00,$0D,$50,$00,$07,$60
.byte $00,$01,$E0,$00,$01,$48,$00,$0F,$C8,$00,$3F,$C0,$00,$3C,$C0,$00
.byte $0D,$F0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8A



// SpriteSet Attribute Data...
// 12 attributes, 1 per image, 8 bits each, total size is 12 ($C) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spritesbatch1_spriteset_attrib_data:

.byte $8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A



