
// Generated by SpritePad C64 - Subchrist Software, 2003-2025.
// Assemble with 64TASS or similar.


// Colour values...

.const spritesbatch1_COLR_VIC_SCREEN = 15
.const spritesbatch1_COLR_VIC_SPRITE_MC1 = 1
.const spritesbatch1_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.const spritesbatch1_SPRITE_COUNT = 13


// Data block sizes (in bytes)...

.const spritesbatch1_SZ_SPRITESET_DATA = 832
.const spritesbatch1_SZ_SPRITESET_ATTRIB_DATA = 13


// Data block addresses (dummy values)...

.const spritesbatch1_addr_spritesbatch1_spriteset_data = $1000
.const spritesbatch1_addr_spritesbatch1_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 13 images, 64 bytes per image, total size is 832 ($340) bytes.

spritesbatch1_spriteset_data:

spritesbatch1_sprite_image_0:
.byte $03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a,$a0,$00,$3e
.byte $40,$00,$0e,$80,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$af,$e8,$00,$8f,$c8,$00,$0c,$c0,$00
.byte $0c,$c0,$00,$0c,$c0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_1:
.byte $00,$00,$00,$03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a
.byte $a0,$00,$3e,$40,$00,$0e,$80,$00,$02,$00,$00,$07,$00,$00,$15,$c8
.byte $00,$25,$68,$00,$05,$00,$00,$0f,$00,$00,$3f,$00,$00,$3f,$00,$00
.byte $73,$00,$00,$73,$c0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_2:
.byte $03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a,$a0,$00,$3e
.byte $40,$00,$0e,$80,$00,$02,$08,$00,$05,$e0,$00,$15,$c0,$00,$27,$40
.byte $00,$2d,$00,$00,$85,$00,$00,$8f,$c0,$00,$0f,$f0,$00,$0c,$f0,$00
.byte $3d,$c0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8a

spritesbatch1_sprite_image_3:
.byte $00,$00,$00,$03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a
.byte $a0,$00,$3e,$40,$00,$0e,$80,$00,$02,$00,$00,$05,$e0,$00,$1d,$e0
.byte $00,$27,$40,$00,$a5,$00,$00,$85,$00,$00,$0f,$00,$00,$0f,$00,$00
.byte $0f,$c4,$00,$7f,$f4,$00,$7c,$d0,$00,$40,$50,$00,$40,$00,$00,$8a

spritesbatch1_sprite_image_4:
.byte $00,$00,$00,$0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a
.byte $b0,$00,$06,$f0,$00,$0a,$c0,$00,$02,$00,$00,$03,$40,$00,$8d,$50
.byte $00,$a5,$60,$00,$01,$40,$00,$03,$c0,$00,$03,$f0,$00,$03,$f0,$00
.byte $03,$34,$00,$0f,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_5:
.byte $03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a,$a0,$00,$3e
.byte $40,$00,$0e,$80,$00,$02,$08,$00,$05,$e0,$00,$15,$c0,$00,$27,$40
.byte $00,$2d,$00,$00,$85,$00,$00,$8f,$c0,$00,$0f,$f0,$00,$0c,$f0,$00
.byte $3d,$c0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8a

spritesbatch1_sprite_image_6:
.byte $0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a,$b0,$00,$06
.byte $f0,$00,$0a,$c0,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$af,$e8,$00,$8f,$c8,$00,$0c,$c0,$00
.byte $0c,$c0,$00,$0c,$c0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_7:
.byte $00,$00,$00,$0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a
.byte $b0,$00,$06,$f0,$00,$0a,$c0,$00,$02,$00,$00,$03,$40,$00,$8d,$50
.byte $00,$a5,$60,$00,$01,$40,$00,$03,$c0,$00,$03,$f0,$00,$03,$f0,$00
.byte $03,$34,$00,$0f,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_8:
.byte $0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a,$b0,$00,$06
.byte $f0,$00,$0a,$c0,$00,$82,$00,$00,$2d,$40,$00,$0d,$50,$00,$07,$60
.byte $00,$01,$e0,$00,$01,$48,$00,$0f,$c8,$00,$3f,$c0,$00,$3c,$c0,$00
.byte $0d,$f0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8a

spritesbatch1_sprite_image_9:
.byte $00,$00,$00,$0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a
.byte $b0,$00,$06,$f0,$00,$0a,$c0,$00,$02,$00,$00,$2d,$40,$00,$2d,$d0
.byte $00,$07,$60,$00,$01,$68,$00,$01,$48,$00,$03,$c0,$00,$03,$c0,$00
.byte $4f,$c0,$00,$7f,$f4,$00,$1c,$f4,$00,$14,$04,$00,$00,$04,$00,$8a

spritesbatch1_sprite_image_10:
.byte $00,$00,$00,$03,$c0,$00,$0f,$c0,$00,$0e,$80,$00,$3e,$e0,$00,$3a
.byte $a0,$00,$3e,$40,$00,$0e,$80,$00,$02,$00,$00,$07,$00,$00,$15,$c8
.byte $00,$25,$68,$00,$05,$00,$00,$0f,$00,$00,$3f,$00,$00,$3f,$00,$00
.byte $73,$00,$00,$73,$c0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8a

spritesbatch1_sprite_image_11:
.byte $0f,$00,$00,$0f,$c0,$00,$0a,$c0,$00,$2e,$f0,$00,$2a,$b0,$00,$06
.byte $f0,$00,$0a,$c0,$00,$82,$00,$00,$2d,$40,$00,$0d,$50,$00,$07,$60
.byte $00,$01,$e0,$00,$01,$48,$00,$0f,$c8,$00,$3f,$c0,$00,$3c,$c0,$00
.byte $0d,$f0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8a

spritesbatch1_sprite_image_12:
.byte $00,$c0,$00,$03,$f0,$00,$0f,$bc,$00,$0d,$9c,$00,$0e,$ac,$00,$82
.byte $e0,$80,$a0,$82,$80,$80,$40,$80,$a5,$d6,$80,$05,$d4,$00,$01,$d0
.byte $00,$01,$50,$00,$13,$f1,$00,$1f,$fd,$00,$1f,$fd,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8a



// SpriteSet Attribute Data...
// 13 attributes, 1 per image, 8 bits each, total size is 13 ($d) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spritesbatch1_spriteset_attrib_data:

.byte $8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a,$8a


