
// Generated by SpritePad C64 - Subchrist Software, 2003 - 2023.
// Assemble with 64TASS or similar.


// Colour values...

.const spritesbatch1_COLR_VIC_SCREEN = 15
.const spritesbatch1_COLR_VIC_SPRITE_MC1 = 1
.const spritesbatch1_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.const spritesbatch1_SPRITE_COUNT = 15


// Data block sizes (in bytes)...

.const spritesbatch1_SZ_SPRITESET_DATA = 960
.const spritesbatch1_SZ_SPRITESET_ATTRIB_DATA = 15


// Data block addresses (dummy values)...

.const spritesbatch1_addr_spritesbatch1_spriteset_data = $1000
.const spritesbatch1_addr_spritesbatch1_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 15 images, 64 bytes per image, total size is 960 ($3C0) bytes.

spritesbatch1_spriteset_data:

spritesbatch1_sprite_image_0:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$AF,$E8,$00,$8F,$C8,$00,$0C,$C0,$00
.byte $0C,$C0,$00,$0C,$C0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_1:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$07,$00,$00,$15,$C8
.byte $00,$25,$68,$00,$05,$00,$00,$0F,$00,$00,$3F,$00,$00,$3F,$00,$00
.byte $73,$00,$00,$73,$C0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_2:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$08,$00,$05,$E0,$00,$15,$C0,$00,$27,$40
.byte $00,$2D,$00,$00,$85,$00,$00,$8F,$C0,$00,$0F,$F0,$00,$0C,$F0,$00
.byte $3D,$C0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8A

spritesbatch1_sprite_image_3:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$05,$E0,$00,$1D,$E0
.byte $00,$27,$40,$00,$A5,$00,$00,$85,$00,$00,$0F,$00,$00,$0F,$00,$00
.byte $0F,$C4,$00,$7F,$F4,$00,$7C,$D0,$00,$40,$50,$00,$40,$00,$00,$8A

spritesbatch1_sprite_image_4:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$03,$40,$00,$8D,$50
.byte $00,$A5,$60,$00,$01,$40,$00,$03,$C0,$00,$03,$F0,$00,$03,$F0,$00
.byte $03,$34,$00,$0F,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_5:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $40,$00,$0E,$80,$00,$02,$08,$00,$05,$E0,$00,$15,$C0,$00,$27,$40
.byte $00,$2D,$00,$00,$85,$00,$00,$8F,$C0,$00,$0F,$F0,$00,$0C,$F0,$00
.byte $3D,$C0,$00,$31,$40,$00,$50,$50,$00,$14,$00,$00,$05,$00,$00,$8A

spritesbatch1_sprite_image_6:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$AF,$E8,$00,$8F,$C8,$00,$0C,$C0,$00
.byte $0C,$C0,$00,$0C,$C0,$00,$14,$50,$00,$54,$54,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_7:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$03,$40,$00,$8D,$50
.byte $00,$A5,$60,$00,$01,$40,$00,$03,$C0,$00,$03,$F0,$00,$03,$F0,$00
.byte $03,$34,$00,$0F,$34,$00,$05,$04,$00,$15,$04,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_8:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$82,$00,$00,$2D,$40,$00,$0D,$50,$00,$07,$60
.byte $00,$01,$E0,$00,$01,$48,$00,$0F,$C8,$00,$3F,$C0,$00,$3C,$C0,$00
.byte $0D,$F0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8A

spritesbatch1_sprite_image_9:
.byte $00,$00,$00,$0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A
.byte $B0,$00,$06,$F0,$00,$0A,$C0,$00,$02,$00,$00,$2D,$40,$00,$2D,$D0
.byte $00,$07,$60,$00,$01,$68,$00,$01,$48,$00,$03,$C0,$00,$03,$C0,$00
.byte $4F,$C0,$00,$7F,$F4,$00,$1C,$F4,$00,$14,$04,$00,$00,$04,$00,$8A

spritesbatch1_sprite_image_10:
.byte $00,$00,$00,$03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A
.byte $A0,$00,$3E,$40,$00,$0E,$80,$00,$02,$00,$00,$07,$00,$00,$15,$C8
.byte $00,$25,$68,$00,$05,$00,$00,$0F,$00,$00,$3F,$00,$00,$3F,$00,$00
.byte $73,$00,$00,$73,$C0,$00,$41,$40,$00,$41,$50,$00,$00,$00,$00,$8A

spritesbatch1_sprite_image_11:
.byte $0F,$00,$00,$0F,$C0,$00,$0A,$C0,$00,$2E,$F0,$00,$2A,$B0,$00,$06
.byte $F0,$00,$0A,$C0,$00,$82,$00,$00,$2D,$40,$00,$0D,$50,$00,$07,$60
.byte $00,$01,$E0,$00,$01,$48,$00,$0F,$C8,$00,$3F,$C0,$00,$3C,$C0,$00
.byte $0D,$F0,$00,$05,$30,$00,$14,$14,$00,$00,$50,$00,$01,$40,$00,$8A

spritesbatch1_sprite_image_12:
.byte $28,$2B,$C0,$AA,$AA,$C0,$AA,$AA,$E0,$AB,$AA,$E8,$AC,$3A,$A0,$B0
.byte $2A,$A8,$B2,$AA,$BC,$FA,$80,$AE,$CA,$2A,$AE,$88,$BA,$0E,$AA,$82
.byte $C2,$A2,$02,$C3,$A2,$CA,$CF,$BE,$88,$02,$F0,$AA,$3A,$E8,$20,$38
.byte $0A,$A0,$F8,$80,$03,$C8,$AA,$0F,$28,$2A,$38,$A0,$08,$2A,$80,$8B

spritesbatch1_sprite_image_13:
.byte $00,$28,$00,$0A,$A8,$00,$2A,$8A,$A8,$AB,$EA,$8A,$8B,$A2,$AE,$8A
.byte $88,$22,$8A,$AC,$02,$8F,$BE,$A2,$8E,$EA,$A0,$3C,$2A,$AA,$38,$A8
.byte $80,$2A,$A8,$B2,$2A,$88,$B2,$2A,$A8,$F2,$AB,$A0,$CA,$AA,$E0,$C8
.byte $2A,$C2,$A8,$0A,$AA,$A0,$0A,$AA,$80,$0A,$A0,$00,$00,$00,$00,$82

spritesbatch1_sprite_image_14:
.byte $2A,$80,$00,$3C,$8E,$B0,$F2,$AA,$00,$C2,$28,$02,$8A,$A0,$A2,$8A
.byte $AA,$AA,$AB,$2A,$3A,$AF,$AA,$0A,$BC,$AA,$A8,$B0,$A2,$28,$A2,$AA
.byte $28,$A2,$28,$E8,$AA,$28,$E8,$EA,$A3,$E8,$E2,$20,$A8,$E2,$22,$AC
.byte $E2,$2A,$AC,$AA,$8A,$BC,$BE,$F8,$B0,$8F,$C2,$80,$A0,$0A,$00,$8B



// SpriteSet Attribute Data...
// 15 attributes, 1 per image, 8 bits each, total size is 15 ($F) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spritesbatch1_spriteset_attrib_data:

.byte $8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8A,$8B,$82,$8B



