.segment sprites [start=$5000]

// Generated by SpritePad C64 - Subchrist Software, 2003 - 2023.
// Assemble with 64TASS or similar.


// Colour values...

.var sprites_COLR_VIC_SCREEN = 9
.var sprites_COLR_VIC_SPRITE_MC1 = 1
.var sprites_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.var sprites_SPRITE_COUNT = 4


// Data block sizes (in bytes)...

.var sprites_SZ_SPRITESET_DATA = 256
.var sprites_SZ_SPRITESET_ATTRIB_DATA = 4


// Data block addresses (dummy values)...

.var sprites_addr_spriteset_data = $1000
.var sprites_addr_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 4 images, 64 bytes per image, total size is 256 ($100) bytes.

spriteset_data:

sprite_image_0:
.byte $03,$C0,$00,$0F,$C0,$00,$0E,$80,$00,$3E,$E0,$00,$3A,$A0,$00,$3E
.byte $80,$00,$0E,$80,$00,$02,$00,$00,$17,$50,$00,$57,$54,$00,$47,$44
.byte $00,$87,$48,$00,$85,$48,$00,$AF,$E8,$00,$8F,$C8,$00,$0C,$C0,$00
.byte $0C,$C0,$00,$0C,$C0,$00,$3C,$F0,$00,$FC,$FC,$00,$00,$00,$00,$8A

sprite_image_1:
.byte $FF,$FF,$00,$C0,$03,$00,$A0,$05,$00,$90,$09,$00,$88,$11,$00,$84
.byte $21,$00,$82,$41,$00,$81,$81,$00,$81,$81,$00,$82,$41,$00,$84,$21
.byte $00,$88,$11,$00,$90,$09,$00,$A0,$05,$00,$C0,$03,$00,$FF,$FF,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$07

sprite_image_2:
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$85

sprite_image_3:
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$85



// SpriteSet Attribute Data...
// 4 attributes, 1 per image, 8 bits each, total size is 4 ($4) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spriteset_attrib_data:

.byte $8A,$07,$85,$85



