
// Generated by SpritePad C64 - Subchrist Software, 2003 - 2023.
// Assemble with 64TASS or similar.


// Colour values...

.const spritesbatch2_COLR_VIC_SCREEN = 15
.const spritesbatch2_COLR_VIC_SPRITE_MC1 = 1
.const spritesbatch2_COLR_VIC_SPRITE_MC2 = 0


// Quantities and dimensions...

.const spritesbatch2_SPRITE_COUNT = 6


// Data block sizes (in bytes)...

.const spritesbatch2_SZ_SPRITESET_DATA = 384
.const spritesbatch2_SZ_SPRITESET_ATTRIB_DATA = 6


// Data block addresses (dummy values)...

.const spritesbatch2_addr_spritesbatch2_spriteset_data = $1000
.const spritesbatch2_addr_spritesbatch2_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 6 images, 64 bytes per image, total size is 384 ($180) bytes.

spritesbatch2_spriteset_data:

spritesbatch2_sprite_image_0:
.byte $00,$00,$00,$C0,$00,$00,$30,$00,$00,$30,$20,$00,$F3,$F0,$00,$CE
.byte $94,$00,$3E,$AC,$00,$3F,$FF,$00,$0C,$30,$00,$03,$0C,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B

spritesbatch2_sprite_image_1:
.byte $C0,$00,$00,$C0,$00,$00,$C0,$20,$00,$C3,$F0,$00,$FE,$94,$00,$3E
.byte $AC,$00,$3F,$FF,$00,$0C,$30,$00,$0F,$3C,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B

spritesbatch2_sprite_image_2:
.byte $00,$00,$00,$30,$00,$00,$30,$00,$00,$C0,$20,$00,$C3,$F0,$00,$CE
.byte $94,$00,$FE,$AC,$00,$3F,$FF,$00,$0C,$30,$00,$30,$C0,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B

spritesbatch2_sprite_image_3:
.byte $00,$00,$00,$00,$03,$00,$00,$0C,$00,$08,$0C,$00,$0F,$CF,$00,$16
.byte $B3,$00,$3A,$BC,$00,$FF,$FC,$00,$0C,$30,$00,$30,$C0,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B

spritesbatch2_sprite_image_4:
.byte $00,$03,$00,$00,$03,$00,$08,$03,$00,$0F,$C3,$00,$16,$BF,$00,$3A
.byte $BC,$00,$FF,$FC,$00,$0C,$30,$00,$3C,$F0,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B

spritesbatch2_sprite_image_5:
.byte $00,$00,$00,$00,$0C,$00,$00,$0C,$00,$08,$03,$00,$0F,$C3,$00,$16
.byte $B3,$00,$3A,$BF,$00,$FF,$FC,$00,$0C,$30,$00,$03,$0C,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$8B



// SpriteSet Attribute Data...
// 6 attributes, 1 per image, 8 bits each, total size is 6 ($6) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

spritesbatch2_spriteset_attrib_data:

.byte $8B,$8B,$8B,$8B,$8B,$8B



